### PR TITLE
Finally got rid of fenvs once and for all

### LINKED ISSUE #3: Instead of getfenv or setfenv we should use a virtual fenv instead
Instead of getfenv or setfenv we should use a virtual fenv instead. So we would keep the  luau optimisations.

Also we rely on loadstring the least we possibly can as it introduces potential security issues.

I mean only in the LBI, we shoudnlt use an ENV anywhere else for obvoius reasons.

### PR DESCRIPTION
**Pull request by ccuser44**
Fixes #3

### CODE REVIEW

**Comment by ccuser44** [comment]
I'm not sure if we need any of these loadstring things at all, and honestly it should rather use a scriptbase to run the code.

**Comment by ccuser44** [comment]
And please we should not make the same mistake with UIs. UIs shouldn't use a loadstring at all.

**Comment by Expertcoderz** [comment]
> And please we should not make the same mistake with UIs. UIs shouldn't use a loadstring at all.

I agree, it just feels weird typing out Lua (not even Luau?) code in the form of a string and slows things down without autocomplete/linting/autoformatting and overall makes debugging a pain when it starts to get long/complex.

**Comment by Sceleratis** [comment]
How were notifications dealt with? They rely on loadstring for their onclick when sent serverside because I thought it would be dumb to add hardcoded situations for it client-side

**Comment by ccuser44** [comment]
> How were notifications dealt with? They rely on loadstring for their onclick when sent serverside because I thought it would be dumb to add hardcoded situations for it client-side

This pull request only virtualises the env, the code will still function like normal.

**Pull request merged**
